#docker-compose.yml

version: '3'

services:
  frps:
    container_name: joinyou-server-frps
    image: snowdreamtech/frps:0.56.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./frps:/etc/frp


  coturn:
    container_name: joinyou-server-coturn
    image: flaviostutz/coturn
    network_mode: host
    environment:
      - TURN_USERNAME=${tuser}
      - TURN_PASSWORD=${tpassword}
